import { useState } from "react"
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"
import { HelpCircle } from "lucide-react"

const OTHER_VALUE = "__other__"

// Renders one clarifying question: a header chip, the question text, its option cards,
// and a free-text "Other" option — the same shape as Claude Code's AskUserQuestion popup
// (short question, mutually-exclusive option chips, always an escape hatch to type
// something else) rather than a rigid multiple-choice form.
function QuestionBlock({ question, index, answer, onAnswer }) {
  const isOtherSelected = answer?.selection === OTHER_VALUE

  return (
    <div className="flex flex-col gap-2.5">
      <div className="flex items-center gap-2">
        <span className="text-label font-bold uppercase tracking-wider text-brand bg-brand-tint px-2 py-0.5 rounded">
          {question.header || `Question ${index + 1}`}
        </span>
      </div>
      <p className="text-body text-foreground font-medium leading-snug">{question.question}</p>
      <div className="flex flex-col gap-1.5">
        {question.options.map(opt => {
          const selected = answer?.selection === opt.label
          return (
            <button
              key={opt.label}
              type="button"
              onClick={() => onAnswer({ selection: opt.label, customText: "" })}
              className={`text-left px-3 py-2 rounded-md border transition-colors cursor-pointer ${
                selected
                  ? "border-brand bg-brand-tint text-foreground"
                  : "border-border hover:border-foreground/30 hover:bg-muted/40"
              }`}
            >
              <p className="text-caption font-semibold text-foreground">{opt.label}</p>
              {opt.description && (
                <p className="text-label text-muted-foreground mt-0.5">{opt.description}</p>
              )}
            </button>
          )
        })}
        <button
          type="button"
          onClick={() => onAnswer({ selection: OTHER_VALUE, customText: answer?.customText || "" })}
          className={`text-left px-3 py-2 rounded-md border transition-colors cursor-pointer ${
            isOtherSelected
              ? "border-brand bg-brand-tint text-foreground"
              : "border-border hover:border-foreground/30 hover:bg-muted/40"
          }`}
        >
          <p className="text-caption font-semibold text-foreground">Other</p>
        </button>
        {isOtherSelected && (
          <Input
            autoFocus
            value={answer?.customText || ""}
            onChange={e => onAnswer({ selection: OTHER_VALUE, customText: e.target.value })}
            placeholder="Type your answer…"
            className="text-caption h-9"
          />
        )}
      </div>
    </div>
  )
}

// Blocks the initial submission on 1-4 context-aware clarifying questions when the query
// is genuinely ambiguous in a way that would change what gets built (scope, timeframe,
// metric, dataset) — generated by POST /api/v1/clarify_task, called before submit_task.
// Most queries return zero questions and never show this at all.
export default function ClarifyingQuestionsModal({ open, questions, onConfirm, onSkip }) {
  const [answers, setAnswers] = useState({})

  const setAnswer = (index, value) => setAnswers(a => ({ ...a, [index]: value }))

  const isAnswered = (index) => {
    const a = answers[index]
    if (!a) return false
    return a.selection === OTHER_VALUE ? a.customText.trim().length > 0 : true
  }
  const allAnswered = questions.every((_, i) => isAnswered(i))

  const handleConfirm = () => {
    const resolved = questions.map((q, i) => {
      const a = answers[i]
      const value = a.selection === OTHER_VALUE ? a.customText.trim() : a.selection
      return { question: q.question, answer: value }
    })
    onConfirm(resolved)
    setAnswers({})
  }

  const handleSkip = () => {
    onSkip()
    setAnswers({})
  }

  return (
    <Dialog open={open} onOpenChange={(next) => { if (!next) handleSkip() }}>
      <DialogContent className="max-w-xl max-h-[85vh] flex flex-col gap-0 p-0 overflow-hidden">
        <DialogHeader className="p-6 pb-4">
          <div className="flex items-center gap-2">
            <HelpCircle className="w-4 h-4 text-brand shrink-0" />
            <DialogTitle>A few quick questions first</DialogTitle>
          </div>
          <DialogDescription>
            Answering these sharpens the analysis — scope, timeframe, or metric choices that
            would otherwise be guessed. Skip if you'd rather proceed as-is.
          </DialogDescription>
        </DialogHeader>

        <Separator />

        <div className="flex-1 overflow-y-auto px-6 py-5 flex flex-col gap-6">
          {questions.map((q, i) => (
            <QuestionBlock
              key={q.question}
              question={q}
              index={i}
              answer={answers[i]}
              onAnswer={(value) => setAnswer(i, value)}
            />
          ))}
        </div>

        <Separator />

        <DialogFooter className="p-4 px-6">
          <Button variant="ghost" onClick={handleSkip} className="text-body">
            Skip and analyse as-is
          </Button>
          <Button onClick={handleConfirm} disabled={!allAnswered} className="text-body">
            Continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
